### ISSUE TITLE
Bug exists in evaluation

### ISSUE THREAD

**Issue by BrandonHanx** [OrangeYHChen/TIPCB#1]
https://github.com/OrangeYHChen/TIPCB/blob/93aa7c53bf6f0e7c4f3301779df397ca3b2b81e9/test_model.py#L40-L42

Not all images in the test split are loaded two times. Your process is arbitrary.

In other words, there are 3074 unique images and 6156 unique sentences in the test split. It is obivous 3074 * 2 != 6156....

Your reported results may a little bit higher than the actual ones.

Please point out if I were wrong.

**Comment by OrangeYHChen** [comment]
Thank you for your advice. This bug does exist, and we will further correct it later.
We reviewed the code and the data, and found that there was no problem with the code in 'test_model.py'. The reason for this bug is that we use the re-organized dataset from orignial json file, and 8 text samples are missing in our 'test.csv' file. I apologize for my carelessness.
Compared with 6000 + samples, the missing 8 samples have a very limited impact on the final accuracy. Our experimental performance is still credible. We will further optimize the code in the future. Thank you for your attention again. If you have any questions, please feel free to contact us.

**Comment by BrandonHanx** [comment]
Thanks for your reply. This issue is solved for me.
